apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: "jdbc:mysql://mysql-db-instance.c74qewyu02qd.ca-central-1.rds.amazonaws.com:3306/restaurantdb"
  foodcataloguedb_url: "jdbc:mysql://mysql-db-instance.c74qewyu02qd.ca-central-1.rds.amazonaws.com:3306/foodcataloguedb"
  userdb_url: "jdbc:mysql://mysql-db-instance.c74qewyu02qd.ca-central-1.rds.amazonaws.com:3306/userdb"
  orderdb_url: "mongodb+srv://admin:root1234@atlas-cluster.7viqptr.mongodb.net/"
  eureka_service_address: "http://eureka-0.eureka-service:8761/eureka"


  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
